### ISSUE TITLE
Fuckoff with your copied malware

### ISSUE THREAD

**Issue by iloveyumyumshrimpnoodles** [Lawxsz/fud-grabber#1]
Github isn't a place to sell your shitty "undetected" project, fuckoff.

![gtfo](https://github.com/Lawxsz/fud-grabber/assets/125209101/53c2c131-fe97-4eb4-8a98-290a585c4273)

**Comment by iloveyumyumshrimpnoodles** [comment]
Yeah that's what I thought, you skid

**Comment by Lawxsz** [comment]
> Yeah that's what I thought, you skid

nah, prysmax have Server, Client and API own. ¿Who are u?

**Comment by iloveyumyumshrimpnoodles** [comment]
Oh wow, like that fucking matters! You're still a skid
